formatting:
  Indentation:
    indentSize: 2
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 8
complexity:
  LongParameterList:
    functionThreshold: 12
  NestedBlockDepth:
    threshold: 6
    excludes: "**/OptionsManager.kt"
  ComplexMethod:
    threshold: 25
    excludes: "**/HistoryHandler.kt, **/TabCloseHandler.kt, **/OptionsManager.kt, **/SearchHelperKt.kt"
  ComplexCondition:
    threshold: 6
  TooManyFunctions:
    thresholdInClasses: 21
    thresholdInObjects: 15
    thresholdInFiles: 19
  LongMethod:
    excludes: "**/HistoryHandler.kt, **/CmdHandler.kt, **/OptionsManager.kt"
exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
naming:
  ClassNaming:
    excludes: "**/ConfigurationMigrators.kt, **/VersionDetectors.kt"
  MemberNameEqualsClassName:
    active: false
  MatchingDeclarationName:
    excludes: "**/CommandDefinition.kt"
performance:
  SpreadOperator:
    active: false
style:
  MaxLineLength:
    active: false
  ReturnCount:
    max: 5
    excludes: "**/VimMultipleCursorsExtension.kt, **/VisualMotionGroup.kt, **/ExRanges.kt, **/CmdHandler.kt, **/VimShortcutKeyAction.kt"
  MagicNumber:
    active: false
  ForbiddenComment:
    active: false
  ThrowsCount:
    excludes: "**/CommandHandler.kt"
