name: Run example UI Tests
on:
  workflow_dispatch
jobs:
  build-for-ui-test-mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: zulu
          java-version: 11
      - name: Clean
        run: gradle clean
      - name: Run Idea
        run: gradle runIdeForUiTests &
      - name: Wait for Idea started
        uses: jtalk/url-health-check-action@1.5
        with:
          url: http://127.0.0.1:8082
          max-attempts: 15
          retry-delay: 30s
      - name: Tests
        run: gradle testUi
      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-fails-report-mac
          path: |
            build/reports