# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Update Changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
# Workflow run on push is disabled to avoid conflicts when merging PR
#  push:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 300
      - name: Get tags
        run: git fetch --tags origin
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

        # The last successful job was marked with a tag
      - name: Get commit with last workflow
        run: |
          echo "LAST_COMMIT=$(git rev-list -n 1 tags/workflow-changelog)" >> $GITHUB_ENV

      - name: Update changelog
        run: ./gradlew updateChangelog
        env:
          SUCCESS_COMMIT: ${{ env.LAST_COMMIT }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog
          commit_user_name: Alex Plate
          commit_user_email: aleksei.plate@jetbrains.com
          commit_author: Alex Plate <aleksei.plate@jetbrains.com>
          file_pattern: CHANGES.md

      - run: |
          git tag --delete workflow-changelog || true
          git push origin :refs/tags/workflow-changelog || true
          git tag workflow-changelog
          git push origin workflow-changelog